name: CodSpeed Benchmarks
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
  pull_request: null
  workflow_dispatch: null
jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d
      - uses: oxc-project/setup-rust@ecabb7322a2ba5aeedb3612d2a40b86a85cee235
        with:
          save-cache: ${{ github.ref_name == 'main' }}
      - name: Install cargo-codspeed
        uses: taiki-e/install-action@13dbd41804825984afd50ab276518620bcbbf933
        with:
          tool: cargo-codspeed
      - name: Build benchmarks
        run: cargo codspeed build
      - name: Run benchmarks
        uses: CodSpeedHQ/action@4a2aedfd08d5b080b44323af01d72484878354d9
        with:
          upload-url: ${{ secrets.CODSPEED_FRANCOIS_DEV_UPLOAD_URL }}
          mode: simulation
          run: cargo codspeed run
