name: CodSpeed
permissions:
  contents: read
  id-token: write
'on':
  push:
    branches:
    - main
  pull_request: null
jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d
    - uses: oxc-project/setup-rust@ecabb7322a2ba5aeedb3612d2a40b86a85cee235
      with:
        save-cache: ${{ github.ref_name == 'main' }}
    - name: Install cargo-codspeed
      run: cargo install cargo-codspeed@4.4.1
    - name: Build benchmarks
      run: cargo codspeed build
    - name: Run benchmarks
      uses: CodSpeedHQ/action@4.4.1
      with:
        upload-url: ${{ secrets.CODSPEED_FRANCOIS_DEV_UPLOAD_URL }}
        mode: simulation
        run: cargo codspeed run
