name: CodSpeed Benchmarks
permissions:
  contents: read
  id-token: write
'on':
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}
jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d
    - uses: oxc-project/setup-rust@ecabb7322a2ba5aeedb3612d2a40b86a85cee235
      with:
        save-cache: ${{ github.ref_name == 'main' }}
    - name: Install cargo-codspeed
      uses: taiki-e/install-action@0afe6f72046bb410622c3b7a43c1e094b6bc3a7c
      with:
        tool: cargo-codspeed
    - name: Build benchmarks
      run: cargo codspeed build
    - name: Run benchmarks
      uses: CodSpeedHQ/action@4.4.1
      with:
        upload-url: ${{ secrets.CODSPEED_FRANCOIS_DEV_UPLOAD_URL }}
        mode: simulation
        run: cargo codspeed run
